### ISSUE TITLE
Feature Req: PHPMyAdmin installed with docker-compose.yml

### ISSUE THREAD

**Issue by muzzwood** [vh/docker-modx#13]
It would be great to get PHPMyAdmin added into the docker-compose.yml file.

**Comment by vh** [comment]
I think this is not issue for image, you can easily add it to your docker-compose.yml if you want:
```
myadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db
  ports:
    - 8080:8080
```
By the way probably it would be helpful to describe such cases in wiki.
