### ISSUE TITLE
Specify volume name so it's not created as a hash

### ISSUE THREAD

**Issue by muzzwood** [vh/docker-modx#14]
Currently the working directory on the host machine is created with a hash because the volume name isn't specified in the docker-compose.yml file.

Also being able to choose where the volume is mounted on the host would be great. Currently everything goes into /var/lib/docker

https://docs.docker.com/compose/compose-file/#volume-configuration-reference

**Comment by muzzwood** [comment]
It appears that version 2 of the docker-compose.yml file is required to be able to name volumes. 
I'm also trying to get the mounted volume out of /var/lib/docker and into my /home dir so I can easily edit the files on the host.
So far I have:
```
version: '2'

services:
    web:
      image: modx
      volumes: 
        - html:/home/digitalpenguin/dev/modxdev
      links:
        - db:mysql
      ports:
        - 80:80
    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: example
      ports:
        - 3306:3306
      command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
    myadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db:db
      ports:
        - 8080:8080
        
volumes:
    html:
        external: false
```

But unfortunately this causes the docker_web_1 container to exit as soon as it's created. Any idea what might be the problem with this syntax?
