### ISSUE TITLE
Issue during setup when using mysql instead of mariadb

### ISSUE THREAD

**Issue by vh** [vh/docker-modx#5]
docker-compose.yml

```
web:
  image: modx
  links:
    - db:mysql
  ports:
    - 80:80
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
```

```
(ERROR @ /setup/index.php) Error HY000 executing statement:
INSERT INTO `system_settings` (`key`, `value`, `xtype`, `namespace`, `area`) VALUES ('upload_maxsize', '2097152', 'textfield', 'core', 'system')
Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'editedon' doesn't have a default value
)
```

**Comment by Mark-H** [comment]
Sounds like MySQL strict mode is enabled; there are some known issues with that (though I don't immediately know the issue numbers)

**Comment by vh** [comment]
Issue appears with both mysql:5.7 and mysql:5.6
I've found the key `mysqld --explicit_defaults_for_timestamp` will check it. It seems default timestamps are deprecated since MySQL 5.6

**Comment by vh** [comment]
Doesn't help

**Comment by rthrash** [comment]
It works with Maria, though, and only MySQL is failing?

**Comment by vh** [comment]
@rthrash yes, only MySQL. With MariaDb works fine!
Probably the reason is in strict mode as Mark said. I found in my.cnf
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

**Comment by rthrash** [comment]
I suspect the fix will be similar to the recent one that was made for MySQL
5.7 in the main Revo installer.
On Fri, Apr 22, 2016 at 2:36 PM Vadim Homchik notifications@github.com
wrote:

> @rthrash https://github.com/rthrash yes, only MySQL. With MariaDb works
> fine!
> Probably the reason is in strict mode as Mark said. I found in my.cnf
> sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/vh/docker-modx/issues/5#issuecomment-213563664
> 
> ## 

## 

[image: photo]
_Ryan Thrash_
Co-founder & CEO, MODX
p:+1 214-682-5050 | e:ryan@modx.com | w:http://modx.com
http://us.linkedin.com/in/ryanthrash  http://twitter.com/rthrash
http://facebook.com/rthrash

**Comment by vh** [comment]
yeah! If to run mysql as `mysqld --sql-mode=NO_ENGINE_SUBSTITUTION` all works fine!

```
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: example
  command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
```
